# Generated by Django 4.2.23 on 2025-06-30 02:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be greater than 0!')])),
                ('number_of_strings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(6, message='Must have at least 6 strings!')])),
            ],
        ),
        migrations.CreateModel(
            name='Guitar_Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guitar_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarsenal.guitar_model')),
            ],
        ),
        migrations.CreateModel(
            name='Current_Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuning', models.CharField(max_length=100)),
                ('string_gauge', models.CharField(max_length=100)),
                ('string_brand', models.CharField(max_length=100)),
                ('string_change_date', models.DateField(auto_now_add=True)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarsenal.guitar_model')),
            ],
        ),
    ]
