# Generated by Django 4.2.23 on 2025-07-01 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarsenal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_model',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Price must be greater than 0!')]),
        ),
    ]
