# Generated by Django 4.2.23 on 2025-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarsenal', '0002_alter_guitar_model_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_pictures',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='media/'),
        ),
    ]
