# Generated by Django 4.2.23 on 2025-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarsenal', '0003_alter_guitar_pictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar_pictures',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='guitar_photos/'),
        ),
    ]
