# Generated by Django 4.2.23 on 2025-07-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarsenal', '0004_alter_guitar_pictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar_model',
            name='additional_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='body_wood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='fretboard_wood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='neck_wood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='num_frets',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='pickup_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='scale_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guitar_model',
            name='top_wood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
